import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner'
import Sidebar from '@/components/SideBar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
    <html lang="en" className="h-full antialiased dark">
      <body className="h-full flex overflow-hidden bg-[#1d1d1d]">
        <Toaster richColors position="top-right" />
        
        {/* Sidebar stays fixed */}
        <Sidebar />

        {/* This main area is what scrolls/changes */}
        <main className="flex-1 relative flex flex-col overflow-hidden">
          {children}
        </main>
        
      </body>
    </html>
  );
}
